"""This type stub file was generated by pyright."""

from typing import Any

from django.db.backends.base.base import BaseDatabaseWrapper

"""
This type stub file was generated by pyright.
"""

class BaseDatabaseClient:
    executable_name: Any = ...
    connection: Any = ...
    def __init__(self, connection: BaseDatabaseWrapper) -> None: ...
    def runshell(self) -> None: ...
