"""This type stub file was generated by pyright."""

from django.dispatch.dispatcher import Signal as Signal
from django.dispatch.dispatcher import receiver as receiver

"""
This type stub file was generated by pyright.
"""
