"""This type stub file was generated by pyright."""

from django.core import validators

"""
This type stub file was generated by pyright.
"""

class ASCIIUsernameValidator(validators.RegexValidator): ...
class UnicodeUsernameValidator(validators.RegexValidator): ...
