"""This type stub file was generated by pyright."""

from collections.abc import Callable
from typing import Any

"""
This type stub file was generated by pyright.
"""

def get_callable(lookup_view: Callable[..., Any] | str) -> Callable[..., Any]: ...
def get_mod_func(callback: str) -> tuple[str, str]: ...
