"""This type stub file was generated by pyright."""

from ninja.orm.factory import create_schema
from ninja.orm.fields import register_field
from ninja.orm.metaclass import ModelSchema

__all__ = ["ModelSchema", "create_schema", "register_field"]
