"""This type stub file was generated by pyright."""

from typing import Any

from django.db.models import Model
from ninja.schema import Schema

__all__ = ["SchemaFactory", "create_schema", "factory"]
type SchemaKey = tuple[type[Model], str, int, str, str, str, str]

class SchemaFactory:
    def __init__(self) -> None: ...
    def create_schema(
        self,
        model: type[Model],
        *,
        name: str = ...,
        depth: int = ...,
        fields: list[str] | None = ...,
        exclude: list[str] | None = ...,
        optional_fields: list[str] | None = ...,
        custom_fields: list[tuple[str, Any, Any]] | None = ...,
        base_class: type[Schema] = ...,
    ) -> type[Schema]: ...
    def get_key(
        self,
        model: type[Model],
        name: str,
        depth: int,
        fields: str | list[str] | None,
        exclude: list[str] | None,
        optional_fields: list[str] | str | None,
        custom_fields: list[tuple[str, str, Any]] | None,
    ) -> SchemaKey:
        """Returns a hashable value for all given parameters"""

factory = ...
create_schema = ...
