"""This type stub file was generated by pyright."""

from abc import ABC, abstractmethod
from typing import Any

from django.http import HttpRequest

__all__ = ["AuthBase", "SecuritySchema"]

class SecuritySchema(dict):
    def __init__(self, type: str, **kwargs: Any) -> None: ...

class AuthBase(ABC):
    def __init__(self) -> None: ...
    @abstractmethod
    def __call__(self, request: HttpRequest) -> Any | None: ...
