"""This type stub file was generated by pyright."""

from typing import Any

from django.http import HttpRequest
from ninja.security.apikey import APIKeyCookie

__all__ = ["SessionAuth", "SessionAuthIsStaff", "SessionAuthSuperUser"]

class SessionAuth(APIKeyCookie):
    """Reusing Django session authentication"""

    param_name: str = ...
    def authenticate(self, request: HttpRequest, key: str | None) -> Any | None: ...

class SessionAuthSuperUser(APIKeyCookie):
    """Reusing Django session authentication & verify that the user is a super user"""

    param_name: str = ...
    def authenticate(self, request: HttpRequest, key: str | None) -> Any | None: ...

class SessionAuthIsStaff(SessionAuthSuperUser):
    def authenticate(self, request: HttpRequest, key: str | None) -> Any | None: ...
