# Generated by Django 5.2 on 2025-04-13 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_database", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bookcase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="MediaCaseDimensions",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("media_format", models.CharField(choices=[("DVD", "DVD"), ("BD", "Blu-ray"), ("VHS", "VHS"), ("4K", "4K UHD")], max_length=3)),
                ("description", models.CharField(max_length=255)),
                ("width", models.DecimalField(decimal_places=2, max_digits=5)),
                ("height", models.DecimalField(decimal_places=2, max_digits=5)),
                ("depth", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                "verbose_name": "Media Case Dimensions",
                "verbose_name_plural": "Media Case Dimensions",
            },
        ),
        migrations.AlterField(
            model_name="collection",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="movie",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="Shelf",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("position_from_top", models.PositiveSmallIntegerField()),
                ("bookcase", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="shelves", to="movie_database.bookcase")),
            ],
            options={
                "ordering": ("position_from_top",),
            },
        ),
        migrations.CreateModel(
            name="PhysicalMedia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("position_on_shelf", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("media_format", models.CharField(choices=[("DVD", "DVD"), ("BD", "Blu-ray"), ("VHS", "VHS"), ("4K", "4K UHD")], max_length=3)),
                ("notes", models.TextField(blank=True)),
                ("movies", models.ManyToManyField(related_name="media_copies", to="movie_database.movie")),
                ("shelf", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="movie_database.shelf")),
            ],
            options={
                "verbose_name": "Physical Media",
                "verbose_name_plural": "Physical Media",
                "ordering": ("shelf__position_from_top", "position_on_shelf"),
            },
        ),
        migrations.AddConstraint(
            model_name="shelf",
            constraint=models.UniqueConstraint(fields=("bookcase", "position_from_top"), name="unique_shelf_position_from_top"),
        ),
        migrations.AddConstraint(
            model_name="physicalmedia",
            constraint=models.UniqueConstraint(fields=("shelf", "position_on_shelf"), name="unique_position_on_shelf"),
        ),
    ]
