# Generated by Django 5.2 on 2025-04-13 04:51

from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

from movie_database.models import MediaFormat


def add_bluray_dimensions(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:  # noqa: ARG001
    """Add Blu-ray dimensions to the MediaCaseDimensions model."""
    MediaCaseDimensions = apps.get_model("movie_database", "MediaCaseDimensions")

    # Define Blu-ray standards in mm (W x H x D)
    dimensions_to_add: list[dict[str, str | float]] = [
        {
            "media_format": MediaFormat.BLURAY,
            "description": "Blu-ray (US Standard)",
            "width": 128.50,
            "height": 148.00,
            "depth": 12.00,
        },
        {
            "media_format": MediaFormat.BLURAY,
            "description": "Blu-ray (UK Standard)",
            "width": 148.00,
            "height": 129.00,
            "depth": 14.00,
        },
        {
            "media_format": MediaFormat.DVD,
            "description": "DVD (Standard)",
            "width": 130.00,
            "height": 184.00,
            "depth": 14.00,
        },
    ]

    for dims in dimensions_to_add:
        MediaCaseDimensions.objects.update_or_create(
            **dims,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("movie_database", "0002_bookcase_mediacasedimensions_alter_collection_name_and_more"),
    ]

    operations = [
        migrations.RunPython(add_bluray_dimensions),
    ]
