# Generated by Django 5.2 on 2025-04-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_database", "0003_add_media_dimensions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookcase",
            name="description",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="bookcase",
            name="location",
            field=models.CharField(max_length=255),
        ),
    ]
