# Generated by Django 5.2 on 2025-04-18 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_database", "0004_alter_bookcase_description_alter_bookcase_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="physicalmedia",
            name="case_dimensions",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="media_dimensions",
                to="movie_database.mediacasedimensions",
            ),
            preserve_default=False,
        ),
    ]
