# Generated by Django 5.2 on 2025-04-18 03:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movie_database", "0005_physicalmedia_case_dimensions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="physicalmedia",
            name="media_format",
        ),
    ]
