# Generated by Django 5.2 on 2025-04-19 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_database", "0006_remove_physicalmedia_media_format"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="movies",
        ),
        migrations.AddField(
            model_name="collection",
            name="physical_media",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name="collections", to="movie_database.physicalmedia"),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="TMDbProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tmdb_id", models.PositiveIntegerField(unique=True)),
                ("adult", models.BooleanField(default=False)),
                ("movie", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="tmdb", to="movie_database.movie")),
            ],
        ),
    ]
