# Generated by Django 5.2 on 2025-04-19 03:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_database", "0007_remove_collection_movies_collection_physical_media_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="release_year",
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1888), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
