# Generated by Django 5.2 on 2025-04-26 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_database", "0008_alter_movie_release_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="physical_media",
        ),
        migrations.AddField(
            model_name="physicalmedia",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="physical_media",
                to="movie_database.collection",
            ),
        ),
    ]
