# Generated by Django 5.2 on 2025-04-26 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_database", "0009_remove_collection_physical_media_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShelfDimensions",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("width", models.DecimalField(decimal_places=2, max_digits=5)),
                ("height", models.DecimalField(decimal_places=2, max_digits=5)),
                ("depth", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                "verbose_name": "Shelf Dimensions",
                "verbose_name_plural": "Shelf Dimensions",
            },
        ),
        migrations.AddField(
            model_name="shelf",
            name="dimensions",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shelf_dimensions",
                to="movie_database.shelfdimensions",
            ),
            preserve_default=False,
        ),
    ]
