# Generated by Django 5.2.4 on 2025-07-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_database", "0010_shelfdimensions_shelf_dimensions"),
    ]

    operations = [
        migrations.AddField(
            model_name="shelf",
            name="orientation",
            field=models.CharField(choices=[("V", "Vertical"), ("H", "Horizontal")], default="V", max_length=1),
        ),
    ]
