# Generated by Django 5.2.4 on 2025-07-15 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_database', '0011_shelf_orientation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tmdbprofile',
            name='adult',
        ),
    ]
