# Generated by Django 5.2.4 on 2025-07-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_database", "0012_remove_tmdbprofile_adult"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="letterboxd_uri",
            field=models.URLField(default="https://boxd.it/29dm"),
            preserve_default=False,
        ),
    ]
