# Generated by Django 5.2.4 on 2025-07-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_database", "0013_movie_letterboxd_uri"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="watched",
            field=models.BooleanField(default=False),
        ),
    ]
