# Generated by Django 5.2.4 on 2025-07-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_database", "0014_movie_watched"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="movie",
            constraint=models.UniqueConstraint(fields=("title", "release_year", "letterboxd_uri"), name="unique_movie"),
        ),
    ]
