# Generated by Django 5.2.4 on 2025-07-24 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_database", "0015_movie_unique_movie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="physicalmedia",
            name="case_dimensions",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="physical_media_set", to="movie_database.mediacasedimensions"),
        ),
        migrations.AlterField(
            model_name="physicalmedia",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="physical_media_set",
                to="movie_database.collection",
            ),
        ),
        migrations.AlterField(
            model_name="physicalmedia",
            name="movies",
            field=models.ManyToManyField(related_name="physical_media_set", to="movie_database.movie"),
        ),
        migrations.AlterField(
            model_name="physicalmedia",
            name="shelf",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="physical_media_set",
                to="movie_database.shelf",
            ),
        ),
        migrations.AlterField(
            model_name="shelf",
            name="dimensions",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="shelves", to="movie_database.shelfdimensions"),
        ),
    ]
