# Generated by Django 5.2.4 on 2025-07-28 04:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movie_database", "0016_alter_physicalmedia_case_dimensions_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={"ordering": ("release_year", "title")},
        ),
    ]
