# Generated by Django 5.2.4 on 2025-08-07 01:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movie_database", "0017_alter_movie_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MediaCaseDimensions",
            new_name="MediaCaseDimension",
        ),
    ]
