# Generated by Django 5.2.4 on 2025-08-07 01:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movie_database", "0018_rename_mediacasedimensions_mediacasedimension"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ShelfDimensions",
            new_name="ShelfDimension",
        ),
    ]
