# Generated by Django 5.2.4 on 2025-08-07 02:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_database", "0019_rename_shelfdimensions_shelfdimension"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediacasedimension",
            name="depth",
            field=models.DecimalField(decimal_places=2, help_text="Width in mm", max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name="mediacasedimension",
            name="height",
            field=models.DecimalField(decimal_places=2, help_text="Width in mm", max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name="mediacasedimension",
            name="width",
            field=models.DecimalField(decimal_places=2, help_text="Width in mm", max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name="shelfdimension",
            name="depth",
            field=models.DecimalField(decimal_places=2, help_text="Width in mm", max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name="shelfdimension",
            name="height",
            field=models.DecimalField(decimal_places=2, help_text="Width in mm", max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name="shelfdimension",
            name="width",
            field=models.DecimalField(decimal_places=2, help_text="Width in mm", max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
