# Generated by Django 5.2.4 on 2025-08-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_database", "0020_alter_mediacasedimension_depth_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="physicalmedia",
            name="unique_position_on_shelf",
        ),
        migrations.AddConstraint(
            model_name="physicalmedia",
            constraint=models.UniqueConstraint(
                condition=models.Q(("position_on_shelf", None), _negated=True),
                fields=("shelf", "position_on_shelf"),
                name="unique_position_on_shelf",
            ),
        ),
    ]
