# Generated by Django 5.2.4 on 2025-08-07 05:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movie_database", "0021_remove_physicalmedia_unique_position_on_shelf_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="physicalmedia",
            old_name="case_dimensions",
            new_name="dimensions",
        ),
    ]
