"""This type stub file was generated by pyright."""

from ninja.files import UploadedFile
from ninja.filter_schema import FilterSchema
from ninja.main import NinjaAPI
from ninja.openapi.docs import Redoc, Swagger
from ninja.orm import ModelSchema
from ninja.params import Body, BodyEx, Cookie, CookieEx, File, FileEx, Form, FormEx, Header, HeaderEx, P, Path, PathEx, Query, QueryEx
from ninja.patch_dict import PatchDict
from ninja.router import Router
from ninja.schema import Schema
from pydantic import Field

"""Django Ninja - Fast Django REST framework"""
__version__ = ...
__all__ = [
    "Body",
    "BodyEx",
    "Cookie",
    "CookieEx",
    "Field",
    "File",
    "FileEx",
    "FilterSchema",
    "Form",
    "FormEx",
    "Header",
    "HeaderEx",
    "ModelSchema",
    "NinjaAPI",
    "P",
    "PatchDict",
    "Path",
    "PathEx",
    "Query",
    "QueryEx",
    "Redoc",
    "Router",
    "Schema",
    "Swagger",
    "UploadedFile",
]
