"""This type stub file was generated by pyright."""

from typing import Any

__all__ = ["NOT_SET"]

class NOT_SET_TYPE:
    def __copy__(self) -> Any: ...
    def __deepcopy__(self, memodict: dict | None = ...) -> Any: ...

NOT_SET = ...
