"""This type stub file was generated by pyright."""

from collections.abc import Callable
from typing import Any

from ninja.types import TCallable

def decorate_view(*decorators: Callable[..., Any]) -> Callable[[TCallable], TCallable]: ...
