"""This type stub file was generated by pyright."""

from collections.abc import Callable
from typing import Any

from django.core.files.uploadedfile import UploadedFile as DjangoUploadedFile

__all__ = ["UploadedFile"]

class UploadedFile(DjangoUploadedFile):
    @classmethod
    def __get_pydantic_json_schema__(cls, core_schema: Any, handler: Callable[..., Any]) -> dict: ...
    @classmethod
    def __get_pydantic_core_schema__(cls, source: Any, handler: Callable[..., Any]) -> Any: ...
