"""This type stub file was generated by pyright."""

from django.http import HttpRequest
from django.utils.datastructures import MultiValueDict
from ninja.types import DictStrAny

__all__ = ["Parser"]

class Parser:
    """Default json parser"""

    def parse_body(self, request: HttpRequest) -> DictStrAny: ...
    def parse_querydict(self, data: MultiValueDict, list_fields: list[str], request: HttpRequest) -> DictStrAny: ...
