"""This type stub file was generated by pyright."""

from collections.abc import Callable
from typing import Any, TypeVar

__all__ = ["DictStrAny", "TCallable"]
type DictStrAny = dict[str, Any]
TCallable = TypeVar("TCallable", bound=Callable[..., Any])
