"""This type stub file was generated by pyright."""

from typing import TYPE_CHECKING, Any

from ninja import NinjaAPI

if TYPE_CHECKING: ...
__all__ = ["get_openapi_urls", "get_root_url"]

def get_openapi_urls(api: NinjaAPI) -> list[Any]: ...
def get_root_url(api: NinjaAPI) -> Any: ...
