"""This type stub file was generated by pyright."""

from typing import TYPE_CHECKING, Any, NoReturn

from django.http import HttpRequest, HttpResponse
from ninja import NinjaAPI

if TYPE_CHECKING: ...

def default_home(request: HttpRequest, api: NinjaAPI, **kwargs: Any) -> NoReturn:
    """This view is mainly needed to determine the full path for API operations"""

def openapi_json(request: HttpRequest, api: NinjaAPI, **kwargs: Any) -> HttpResponse: ...
def openapi_view(request: HttpRequest, api: NinjaAPI, **kwargs: Any) -> HttpResponse: ...
