"""This type stub file was generated by pyright."""

from typing import Any

"""
This type stub file was generated by pyright.
"""

class CheckFieldDefaultMixin:
    def check(self, **kwargs: Any) -> list[Any]: ...
