"""This type stub file was generated by pyright."""

from typing import Any

from django.utils.decorators import sync_and_async_middleware

FIX_MIDDLEWARE_PATH: str = ...
FIX_METHODS = ...

def need_to_fix_request_files(methods: list[str], params_models: list[Any]) -> bool: ...
@sync_and_async_middleware
def fix_request_files_middleware(get_response: Any) -> Any:
    """This middleware fixes long historical Django behavior where request.FILES is only
    populated for POST requests.
    https://code.djangoproject.com/ticket/12635
    """
