"""This type stub file was generated by pyright."""

from http import cookies

"""
This type stub file was generated by pyright.
"""
SimpleCookie = cookies.SimpleCookie

def parse_cookie(cookie: str) -> dict[str, str]: ...
