"""This type stub file was generated by pyright."""

from collections.abc import Sequence
from typing import Any

from django.apps.config import AppConfig
from django.core.checks.messages import Warning

"""
This type stub file was generated by pyright.
"""

def check_all_models(app_configs: Sequence[AppConfig] | None = ..., **kwargs: Any) -> list[Warning]: ...
def check_lazy_references(app_configs: Sequence[AppConfig] | None = ..., **kwargs: Any) -> list[Any]: ...
