"""This type stub file was generated by pyright."""

from typing import Any, Self, overload

"""
This type stub file was generated by pyright.
"""

class SafeData:
    def __html__(self) -> Self: ...

class SafeText(str, SafeData):
    @overload
    def __add__(self, rhs: SafeText) -> SafeText: ...
    @overload
    def __add__(self, rhs: str) -> str: ...
    @overload
    def __iadd__(self, rhs: SafeText) -> SafeText: ...
    @overload
    def __iadd__(self, rhs: str) -> str: ...

SafeString = SafeText

def mark_safe(s: Any) -> SafeText: ...
