name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
    - name: Install Dependencies
      run: |
        poetry install --no-interaction
    - name: Run Tests
      run: |
        python manage.py test
